#anigamerplus latest release build

name: aniGamerPlus Build Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: v24.7)'
        required: true
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python: [3.11.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
          python-version: ${{ matrix.python }}

    - name: Set up ENV
      run: |
        chcp 65001
        if ("${{ github.event_name }}" -eq "workflow_dispatch") {
          $version = "${{ inputs.version }}"
        } else {
          $version = "${{ github.ref_name }}"
        }
        echo ("RELEASE_VERSION=" + $version) >> $env:GITHUB_ENV
        echo ("RELEASE_TITLE=aniGamerPlus_" + $version + "_windows_64bit") >> $env:GITHUB_ENV
        echo ("RELEASE_FILENAME=aniGamerPlus_" + $version + "_windows_64bit.zip") >> $env:GITHUB_ENV
        git fetch --tags --force
    - name: Get tag message
      id: tag_data
      run: |
        $tagMessage = git tag -l --format='%(contents)' $env:RELEASE_VERSION
        echo "git-tag-annotation<<EOF" >> $env:GITHUB_OUTPUT
        echo $tagMessage >> $env:GITHUB_OUTPUT
        echo "EOF" >> $env:GITHUB_OUTPUT
    - name: Test ENV
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
        echo $RELEASE_TITLE
        echo ${{ env.RELEASE_TITLE }}
        echo $RELEASE_FILENAME
        echo ${{ env.RELEASE_FILENAME }}
        echo $TAG_MESSAGE
        echo '${{ steps.tag_data.outputs.git-tag-annotation }}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build exe
      run: pyinstaller --noconfirm --distpath %cd%\ --onefile --console --icon %cd%\Dashboard\static\img\aniGamerPlus.ico --clean --add-data %cd%;aniGamerPlus/  %cd%\aniGamerPlus.py
      shell: cmd

    - name: Archive release
      run: 7z a -tzip ${{ env.RELEASE_FILENAME }} aniGamerPlus.exe Dashboard DanmuTemplate.ass config-sample.json sn_list-sample.txt LICENSE README.md

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        name: "${{ env.RELEASE_TITLE }}"
        body: ${{ steps.tag_data.outputs.git-tag-annotation }}
        draft: false
        prerelease: false
        files: ./${{ env.RELEASE_FILENAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
